name: my_quotes
description: Mobile app for storing personal quotes

version: 1.2.2+122

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: 3.41.6

dependencies:
  flutter:
    sdk: flutter

  provider: 6.1.5+1
  get_it: 9.2.1
  rxdart: 0.28.0
  hive: 2.2.3
  path_provider: 2.1.5
  share_plus: 12.0.2
  url_launcher: 6.3.2

  collection: any
dev_dependencies:
  very_good_analysis: 7.0.0
  hive_generator: 2.0.1
  build_runner:

flutter:
  uses-material-design: true

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/icons/icomoon.ttf
